language: cpp
os: linux

jobs:
  include:
    - os: linux
      compiler: gcc
      dist: bionic
      env:
        - MATRIX_EVAL="CC=gcc-9"
      before_install:
        - sudo apt-get update
      install:
        - sudo apt-get install cmake
      script:
        - cd src/scripts
        - /bin/bash build.sh
        - /bin/bash start_server.sh &
        - /bin/bash start_client.sh